### ISSUE TITLE
System.OutOfMemoryException starting yesterday

### ISSUE THREAD

**Issue by jholovacs** [nant/nant#162]
We're suddenly seeing this in our build logs (bamboo) starting yesterday:

22-Dec-2015 14:40:38	INTERNAL ERROR
22-Dec-2015 14:40:38	
22-Dec-2015 14:40:38	System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
22-Dec-2015 14:40:38	   at System.String.ReplaceInternal(String oldValue, String newValue)
22-Dec-2015 14:40:38	   at System.String.Replace(String oldValue, String newValue)
22-Dec-2015 14:40:38	   at NAnt.Core.DefaultLogger.OutputMessage(BuildEventArgs e, Int32 indentationLength)
22-Dec-2015 14:40:38	   at NAnt.Core.Tasks.EchoTask.ExecuteTask()
22-Dec-2015 14:40:38	   at NAnt.Core.Task.Execute()
22-Dec-2015 14:40:38	   at NAnt.Core.Target.Execute()
22-Dec-2015 14:40:38	   at NAnt.Core.Project.Execute(String targetName, Boolean forceDependencies)
22-Dec-2015 14:40:38	   at NAnt.Core.Task.Execute()
22-Dec-2015 14:40:38	   at NAnt.Core.Target.Execute()
22-Dec-2015 14:40:38	   at NAnt.Core.Project.Execute(String targetName, Boolean forceDependencies)
22-Dec-2015 14:40:38	   at NAnt.Core.Project.Execute()
22-Dec-2015 14:40:38	   at NAnt.Core.Project.Run()
22-Dec-2015 14:40:38	
22-Dec-2015 14:40:38	Please send bug report to nant-developers@lists.sourceforge.net.

This error occurs against .91 and .92.  Any ideas?

**Comment by ChrisJacquesPayfactors** [comment]
Ditto
